### ISSUE TITLE
System.ArgumentException: 路径中具有非法字符

### ISSUE THREAD

**Issue by bilibiliSTJun** [detached64/GalArc#6]
抱歉打扰，不懂电脑，就是想把喜欢的游戏图片提出来，这种问题该怎么解决
文件位置已经尽可能简化并且没有特殊字符
是不是和windows的环境变量有关，但是我已经换了电脑试过了依旧报相同错误。
运行的版本1.3.2和1.2.4错误相同。
系统环境：win10 21H2

输入文件路径：	C:\Users\STJun\Desktop\1\data02000.arc
输出文件夹路径：	C:\Users\STJun\Desktop\1\data02000
解包中……
检测到arc v2封包。
内部有1230132546个文件。
路径中具有非法字符。
System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.Combine(String path1, String path2)
   在 ArcFormats.AdvHD.ARC.arcV2_unpack(String filePath, String folderPath)
   在 ArcFormats.AdvHD.ARC.Unpack(String filePath, String folderPath)

**Comment by detached64** [comment]
需要先确认游戏的引擎。游戏名字是什么？

**Comment by bilibiliSTJun** [comment]
> 需要先确认游戏的引擎。游戏名字是什么？

名字：“推しのラブより恋のラブ”
文件除exe启动器外均为arc后缀，不知道什么引擎
用16进制编辑 文件头为： BURIKO ARC20 TITLT CAUT00-EN
如果可以的话，我可以将文件发生给您。

**Comment by bilibiliSTJun** [comment]
搜了一下 这个好像是bgi引擎，这个是不是解不了啊QAQ

**Comment by detached64** [comment]
是的，可以使用GARbro
